DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS compilation CASCADE;
DROP TABLE IF EXISTS category CASCADE;
DROP TABLE IF EXISTS request CASCADE;
DROP TABLE IF EXISTS event CASCADE;
DROP TABLE IF EXISTS compilation_events CASCADE;

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email varchar(254),
    name  varchar(250),
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS category
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name varchar(50) NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id),
    CONSTRAINT uq_category_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS event
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    initiator_id       integer                     NOT NULL,
    annotation         varchar(2000)               NOT NULL,
    category_id        integer                     NOT NULL,
    description        varchar(7000)               NOT NULL,
    event_date         timestamp without time zone NOT NULL,
    created_on         timestamp without time zone NOT NULL,
    published_on       timestamp without time zone,
    lat                double precision            NOT NULL,
    lon                double precision            NOT NULL,
    paid               boolean                     NOT NULL,
    participant_limit  integer                     NOT NULL,
    confirmed_requests integer                     NOT NULL,
    request_moderation boolean                     NOT NULL,
    title              varchar(120)                NOT NULL,
    state              varchar(32)                 NOT NULL,
    CONSTRAINT pk_event PRIMARY KEY (id),
    CONSTRAINT fk_e_category_id FOREIGN KEY (category_id) REFERENCES category (id),
    CONSTRAINT fk_e_user_id FOREIGN KEY (initiator_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS request
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created      timestamp without time zone NOT NULL,
    event_id     integer                     NOT NULL,
    requester_id integer                     NOT NULL,
    status       varchar(32)                 NOT NULL,
    CONSTRAINT pk_request PRIMARY KEY (id),
    CONSTRAINT fk_r_event_id FOREIGN KEY (event_id) REFERENCES event (id),
    CONSTRAINT fk_r_requester_id FOREIGN KEY (requester_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS compilation
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    pinned     boolean     NOT NULL,
    title      varchar(50) NOT NULL,
    CONSTRAINT pk_compilation PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS compilation_events
(
    compilation_id BIGINT NOT NULL,
    events_id      BIGINT NOT NULL,
    CONSTRAINT fk_ce_compilation_id FOREIGN KEY (compilation_id) REFERENCES compilation (id) ON DELETE CASCADE,
    CONSTRAINT fk_ce_event_id FOREIGN KEY (events_id) REFERENCES event (id) ON DELETE CASCADE
);
