DROP TABLE IF EXISTS Stats;

CREATE TABLE IF NOT EXISTS Stats
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    app       VARCHAR(64)                 NOT NULL,
    uri       VARCHAR(256)                NOT NULL,
    ip        VARCHAR(64)                 NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT  pk_Stats PRIMARY KEY (id)
);